### PR TITLE
License under GNU GPLv2.0

### PR DESCRIPTION
**Pull request by 173210**
Your program includes code licensed under GPLv2 or any later version.
You **MUST** license your program under one of those license. My patch is to license under GPLv3.
If you don't want to use version 3, you can use version 2 or 2.1.

### CODE REVIEW

**Comment by b1l1s** [comment]
Well mid-kid isn't here to discuss this so I'm going to hold off on this for a while. I'll try to get @Normmatt to change his license perhaps. It looks like it's the only part of the code under GPLv2.

**Comment by b1l1s** [comment]
Also thought on [this](http://www.gnu.org/licenses/license-list.en.html#MPL-2.0)?

**Comment by Syphurith** [comment]
@b1l1s I'm sorry but it (MPL) seems not appliable for this file. See the 2nd para of the article you gave. GPL is quite strict, unlike MPL iirc. Or else you could ask for changing it..
From this [article](http://www.tomhull.com/ocston/docs/mozgpl.html).
_MPL does not permit relicensing, and does impose restrictions which are incompatible with GPL, therefore cannot be used in any GPL-licensed work (program or whatever)._

**Comment by 173210** [comment]
CakeFW, dctr, and rxTools are depend on this project.
CakeFW is licensed under GPLv3. dctr doesn't have a documented license. rxTools was licensed under BSD license, but the current license is not clear because Pasta Team who owns rxTools now has not described their license. It's also a solution to make all of them licensed under GPLv3.

I guess mid-kid uses MPL to make it possible to use CakeHax in projects which don't use GPLv3. If so, we may tell developers that CakeHax uses GPLv2+ code only for SDMMC and we can find a solution for their projects if they want.

**Comment by b1l1s** [comment]
> I guess mid-kid uses MPL to make it possible to use CakeHax in projects which don't use GPLv3

Yup.

> If so, we may tell developers that CakeHax uses GPLv2+ code only for SDMMC and we can find a solution for their projects if they want.

Not sure what you mean by this. Do you mean dual-licensing?

**Comment by 173210** [comment]
I mean we can create non-GPL version by removing GPL code anytime unless we have more external GPL codes.

**Comment by b1l1s** [comment]
Nope there's no more GPL code. I messaged @Normmatt about changing his license. Still no reply from him yet. This would be the best solution I think.

**Comment by 173210** [comment]
I see. What I suggested is just one of solutions.

**Comment by Normmatt** [comment]
From what I understand section 1.12 of the MPL licence you are allowed to use GPLV2 licenced code while the rest is MPL licenced.

**Comment by 173210** [comment]
MPL allows but GPL doesn't.

**Comment by b1l1s** [comment]
@Normmatt Why did you choose GPLv2?

**Comment by dukesrg** [comment]
@17320 I suppose it won't be a big deal to replace cakehax loader with proprietary unencrypted one if this is a problem. I realised its code also depends on p3d fork... Well maybe it's something wrong with my sence of humour but making a ROP chains with Python is not fun at all. The equivalent code in my Spuder3DSTools fork is times smaller and easier to understand :(

**Comment by 173210** [comment]
Hmm, so it may be easier to use GPL in this project.
p3ds is licensed under GPLv2.0, not any later, so this should be licensed under GPLv2.0.

**Comment by b1l1s** [comment]
Nope I am not doing GPL. I'm still discussing options now. But my feeling is to remove p3ds/sdmmc altogether. p3ds stuff can easily be rewritten. sdmmc is tougher but we can port libnds code which is under zlib.

**Comment by 173210** [comment]
Well, @Normmatt, can't you license those files both under MPL and GPL?

**Comment by dukesrg** [comment]
@b1l1s I can help with replacing p3ds with pure gas if you and @mid-kid will decide so!

**Comment by b1l1s** [comment]
@dukesrg. That would be great thanks! @mid-kid isn't here but I think we should do it anyway. Just don't license it under GPL for the love of god.

**Comment by dukesrg** [comment]
@b1l1s I'm not licensing any code I share and not sharing commercial code at all ;)

**Comment by Normmatt** [comment]
Why the hate for GPL? I'm ok with re-licencing the code with a dual MPL/GPL licence just curious why your so against it.

**Comment by b1l1s** [comment]
@dukesrg lol that's great to hear, you should at least slap a MIT license on it though.
@Normmatt I just don't want to make other projects have to choose GPL that's all (re rxTools). Will you really do that for us?

**Comment by b1l1s** [comment]
Well thanks to Normmatt we can use/dist sdmmc.c as dual license now. per 182b2b8d4915a2dfb632f9b6c278765971b8e28a

**Comment by Syphurith** [comment]
Well. So this might be changed. @173210 Eh cause `sdmmc.c` is now dual-licensed (GPLv2+MPL).
@b1l1s Then should a MPL license text be included into the project, or at least state that in Readme?

**Comment by 173210** [comment]
https://github.com/mid-kid/CakeHax/blob/master/LICENSE.txt#L355

```
Exhibit A - Source Code Form License Notice
-------------------------------------------

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.
```

**Comment by Syphurith** [comment]
@173210 so its license is already in the repo. My mistake.

**Comment by b1l1s** [comment]
p3ds removed thanks to dukesrg! Closing the pull request. Thanks everyone for your input and help.

**Pull request closed without merging**
